set -e
sh /builds/build-tcl.sh
sh /builds/build-tclx.sh
sh /builds/build-sqlite3.sh
sh /builds/build-tcllib.sh
sh /builds/build-critcl.sh
sh /builds/build-tcllauncher.sh
sh /builds/build-itcl.sh
sh /builds/build-tclreadline.sh

sh /builds/build-cpptcl.sh
sh /builds/build-scotty-tnm.sh
sh /builds/build-tclbsd.sh
sh /builds/build-yajl-tcl.sh
sh /builds/build-tcltls.sh
sh /builds/build-tdom.sh
sh /builds/build-tclclockmod.sh
sh /builds/build-pgtcl.sh
sh /builds/build-zookeepertcl.sh
sh /builds/build-tclupd.sh
sh /builds/build-tclzlib.sh
